package types

// Module
type (
	// Module represents the structure of a single module, including its metadata and dependencies.
	Module struct {
		// Name is the URL-safe name of the module.
		Name string `yaml:"name"`
		// Description provides a brief summary of the module.
		Description string `yaml:"description"`
		// Version specifies the current version of the module.
		Version string `yaml:"version"`
		// Languages lists the programming languages supported by the module.
		Languages []string `yaml:"languages"`
		// Dependencies maps each language to a list of required dependencies.
		Dependencies map[string][]string `yaml:"dependencies"`
		// Tags provides a list of tags associated with the module.
		Tags []string `yaml:"tags"`
	}
)

// Registry
type (
	// Registry represents the structure of the registry index file containing module and template information.
	Registry struct {
		// Schema specifies the version of the registry schema.
		Schema uint `yaml:"schema"`
		// Modules maps URL-safe module names to their corresponding metadata within the registry.
		Modules map[string]RegistryModuleInfo `yaml:"modules"`
		// Templates maps URL-safe template names to their corresponding metadata within the registry.
		Templates map[string]RegistryTemplateInfo `yaml:"templates"`
	}
	// RegistryModuleInfo represents the metadata for a single module within the registry index.
	RegistryModuleInfo struct {
		// Description provides a brief summary of the module.
		Description string `yaml:"description"`
		// Tags provides a list of tags associated with the module.
		Tags []string `yaml:"tags"`
		// Versions lists the available versions of the module.
		Versions []string `yaml:"versions"`
	}

	// RegistryTemplateInfo represents the metadata for a single project template within the registry index.
	RegistryTemplateInfo struct {
		// Description provides a brief summary of the template.
		Description string `yaml:"description"`
		// Versions lists the available versions of the template.
		Versions []string `yaml:"versions"`
	}
)

// Template
type (
	// Template represents the structure of a single project template, including its metadata.
	AutoGenerated struct {
		// Name is the URL-safe name of the template.
		Name string `yaml:"name"`
		// Version specifies the current version of the template.
		Version string `yaml:"version"`
		// Language specifies the programming language of the template.
		Language string `yaml:"language"`
		// Type specifies the type/category of the template, e.g. "web", "cli", or "library".
		Type string `yaml:"type"`
		// Modules lists the modules used by the template.
		Modules []string `yaml:"modules"`
	}
)
